### ISSUE TITLE
Webform 

### ISSUE THREAD

**Issue by Claonilton** [VTECRM/vtenext#13]
Details: 
version 1.48
PHP 7.4.33

I created a webform but when I try to send a POST externally on the website, the page returns ERROR 500.

Follow the logs:
[Sat Apr 22 18:04:53.672632 2023] [php7:error] [pid 1895] [client 172.31.0.1:38718] PHP Fatal error:  Uncaught Error: Class **'CRMEntity' not found** in /var/www/html/modules/Users/Users.php:18\nStack trace:\n#0 /var/www/html/vtlib/Vtecrm/Event.php(10): include_once()\n#1 /var/www/html/vtlib/Vtecrm/Module.php(17): include_once('/var/www/html/v...')\n#2 /var/www/html/include/utils/CommonUtils.php(11): require_once('/var/www/html/v...')\n#3 /var/www/html/include/ComboUtil.php(7): require_once('/var/www/html/i...')\n#4 /var/www/html/include/utils/utils.php(16): require_once('/var/www/html/i...')\n#5 /var/www/html/data/CRMEntity.php(10): require_once('/var/www/html/i...')\n#6 /var/www/html/include/QueryGenerator/QueryGenerator.php(7): require_once('/var/www/html/d...')\n#7 /var/www/html/modules/Webforms/capture.php(12): include_once('/var/www/html/i...')\n#8 {main}\n  thrown in /var/www/html/modules/Users/Users.php on line 18

Line 18 in Users.php:
`class Users extends CRMEntity { //crmv@392267`

**Comment by 95AlessiaC95** [comment]
@Claonilton I have this problem too. Have you managed to find a solution?

Thank you
