### ISSUE TITLE
Install fails to create one database table

### ISSUE THREAD

**Issue by DarylMeese** [VTECRM/vtenext#64]
While installing VTE it dies with "Tables partially created" on line 499 of CreateTables.inc.php. I have tracked the problem down to one table, vte_check_logins.  The related xml that fails to create is:

  <table name="vte_check_logins">
	<field name="id" type="I" size="19">
		<KEY/>
	</field>
	<field name="userid" type="I" size="19"/>
	<field name="first_attempt" type="DT"/>
	<field name="last_attempt" type="DT"/>
	<field name="ip" type="C" size="50"/>
	<field name="type" type="C" size="50"/>
	<field name="attempts" type="I" size="5">
		<DEFAULT value="0"/>
	</field>
	<field name="status" type="C" size="5"/>
	<field name="date_whitelist" type="DT"/>
	<field name="mailkey" type="C" size="50"/>
	<index name="CheckLoginIndex1">
      <col>ip</col>
      <col>status</col>
    </index>
    <index name="CheckLoginIndex2">
      <col>userid</col>
      <col>ip</col>
      <col>type</col>
      <col>status</col>
    </index>
    <index name="CheckLoginIndex3">
      <col>userid</col>
      <col>ip</col>
      <col>type</col>
    </index>
  </table>

**Comment by davidegiarolo** [comment]
Hi, please give details about your lamp enviroment in order to better help you
ty

**Comment by DarylMeese** [comment]
Insalling locally on a xampp v.3.2.3 setup. Windows 10. Every other table installed fine. only vte_check_logins failed. to be created. 
I got past that error by changing the "die" at line 499 to "echo." Afterward, this was the output.

"Fatal error: Uncaught Error: Call to undefined method adoSchema::ExtractSchema_singletable() in C:\xampp\htdocs\vtenext\include\utils\UserInfoUtil.php:1806 Stack trace: #0 C:\xampp\htdocs\vtenext\include\utils\UserInfoUtil.php(682): UserInfoUtils->historicizeVersionTables('1', Array) #1 C:\xampp\htdocs\vtenext\include\utils\UserInfoUtil.php(1959): UserInfoUtils->closeVersion_role() #2 C:\xampp\htdocs\vtenext\install\CreateTables.php(161): UserInfoUtils->initSystemVersions() #3 C:\xampp\htdocs\vtenext\install.php(62): include('C:\\xampp\\htdocs...') #4 {main} thrown in C:\xampp\htdocs\vtenext\include\utils\UserInfoUtil.php on line 1806"
